# This section handles the load balancer
apiVersion: v1
kind: Service
metadata:
  name: binarycalculator-service
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: binarycalculator
