# This section handles deploying the app to the kluster
apiVersion: apps/v1
kind: Deployment
metatdata:
	name: binarycalculator-deployment
spec:
	replicas: 1
	selector:
		matchLabels:
			app: binarycalculator
	template:
		metadata:
			labels:
				app: binarycalculator
		spec:
			containers:
			      - image: 
				name: binarycalculator
				ports:
				      - containerPort: 8080
					name: binarycalculator

# This section handles the load balancer
apiVersion: v1
kind: Service
metadata:
	name: binarycalculator-service
spec:
	type: LoadBalancer
	ports:
	      - port: 3306
	selector:
		app: binarycalculator
